version: '2.1'
services: 
  delayed-stop:
    build: ./
    image: local
    environment: 
      # Wait 20 seconds before exit
      - TIME_TO_EXIT=20

  well-behaved:
    build: ./
    image: local
    environment:
      - TIME_TO_EXIT=5
